service: stock-api
provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-1
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  stock:
    handler: bin/stock
    events:
      - http:
          path: /stocks/{market}/{ticker}
          method: get
